language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: precise
      python: 2.7
    - os: linux
      dist: precise
      python: 3.5
    - os: linux
      dist: precise
      python: pypy
#    - os: linux
#      dist: precise
#      python: pypy3
install: "pip install coverage python-coveralls"  # or "coveralls" instead (alternative package)
# Removing appdirs to increase code coverage... better would be to test both scenarios (with and without appdirs available)
script: python setup.py build && pip remove appdirs || coverage run --source=configr configr/test.py && coverage html && coverage annotate configr/test.py
after_success:
  - coveralls
